// lens-reader's Worker config, in the TypeScript format `cf migrate` writes.
//
// Generated by `cf migrate wrangler.toml --no-install` (cf 1.0.0-beta.5) on
// 2026-09-28, then edited the way lwe-ask/cloudflare.config.ts was: the toml's
// comments carried over at their keys, the import pointed at
// `@cloudflare/config/public` rather than `cf/config` (cf-garage's config says
// why), and the generator's "Migration incomplete" guard removed. The tooling
// half, minify and source maps, lives in wrangler.config.ts beside this file.
//
// Every wrangler command that reads this passes `--x-new-config` and runs from
// this directory. The upload is byte-identical to the toml's (index.js and the
// source map mappings), measured with `deploy --dry-run --outdir`.
//
// The `cf` CLI does NOT run here, and that is a consequence of this project
// sitting outside the workspace rather than of the config. cf finds a dev server
// by reading THIS directory's package.json, and naming wrangler in it would
// install a second wrangler into lens-reader/node_modules, which check-wrangler
// refuses by design. The format works; wrangler drives it.
import { bindings, defineConfig, triggers } from "@cloudflare/config/public";

export default defineConfig({
  // Pinned because this deploys from its OWN directory, so wrangler resolves the
  // account from this file rather than from the root cloudflare.config.ts. It
  // auto-selects only while the login sees exactly one account, and a second
  // appeared on 2026-08-07. Until the pin existed the answer came from
  // ~/.wrangler/cache/wrangler-account.json, which an interactive prompt
  // writes, so a fresh clone or a cleared cache broke the deploy. Must equal
  // the root cloudflare.config.ts's accountId; check-infra.ts fails on drift.
  accountId: "1c99acdb6141579023fb97d24261ea58",
  worker: {
    name: "lens-reader",
    compatibilityDate: "2026-07-02",
    // `new_module_registry` is not date-gated; the argument is at the same key
    // in the root cloudflare.config.ts, and every Worker here carries it.
    compatibilityFlags: ["nodejs_compat", "new_module_registry"],
    entrypoint: "src/index.ts",

    // Workers Logs, the same free tier the site Worker runs on.
    observability: {
      enabled: true,
      traces: { enabled: true, headSamplingRate: 1 },
    },

    // Intercepts /lens/read* ahead of the site Worker, exactly the way cf-garage
    // intercepts /garage/cf/*. This is a ROUTE and not a `run_worker_first`
    // entry, which is the whole reason the feature lives in its own script: that
    // list is a hard 100 (docs/GOTCHAS.md gotcha 26).
    triggers: [triggers.fetch({ pattern: "aadhar.sh/lens/read*", zone: "aadhar.sh" })],

    env: {
      // Per-IP budget, mirroring the /lens/* family. Extraction is pure CPU with
      // one upstream fetch, so this is cheaper than Browser Run and dearer than a
      // parse: the ceiling sits between /lens/browser (4/min) and /lens/fetch
      // (30/min).
      READER_RL: bindings.rateLimit({ namespace: "3001", simple: { limit: 10, period: 60 } }),
    },
  },
});
