// Generated by tools/xp; run bun tools/gen-xp.ts. Do not edit.
import { Html, html } from "../html.ts";

export type ExplorerItemOptions = {
  href: string;
  label: string;
  glyph?: string;
};

export function ExplorerItem({
  href,
  label,
  glyph = "",
}: ExplorerItemOptions): Html {
  return html`<li><span class="axp-glyph" aria-hidden="true">${glyph || "›"}</span><a href="${href}">${label}</a></li>`;
}

export type ExplorerListOptions = {
  items: ExplorerItemOptions[];
};

export function ExplorerList({
  items,
}: ExplorerListOptions): Html {
  return html`<ul>${items.map(ExplorerItem)}</ul>`;
}
