// Generated by tools/xp; run bun tools/gen-xp.ts. Do not edit.
import { Html, html } from "../html.ts";

export type PropertyRowOptions = {
  term: string;
  value: string;
};

export function PropertyRow({
  term,
  value,
}: PropertyRowOptions): Html {
  return html`<dt>${term}</dt><dd>${value}</dd>`;
}

export type PropertySheetOptions = {
  rows: PropertyRowOptions[];
};

export function PropertySheet({
  rows,
}: PropertySheetOptions): Html {
  return html`<dl>${rows.map(PropertyRow)}</dl>`;
}
