// Generated by tools/xp; run bun tools/gen-xp.ts. Do not edit.
import { Html, html } from "../html.ts";

export type TaskbarOptions = {
  pins: Html;
  tray: Html;
};

export function Taskbar({
  pins,
  tray,
}: TaskbarOptions): Html {
  return html`<div id="axp-taskbar" role="navigation" aria-label="taskbar"><a id="axp-start" href="/run" aria-haspopup="dialog" aria-expanded="false"><span id="axp-cone" aria-hidden="true"></span>start<span class="axp-kbd" aria-hidden="true">⌘K</span></a><div id="axp-pins">${pins}</div><div id="axp-spacer"></div>${tray}</div>`;
}
