// Generated by tools/xp; run bun tools/gen-xp.ts. Do not edit.
import { Html, html } from "../html.ts";
import { asBool } from "../parse.ts";

export type TaskbarPinOptions = {
  href: string;
  label: string;
  hint: string;
  count: number;
  icon: Html;
};

export function TaskbarPin({
  href,
  label,
  hint,
  count,
  icon,
}: TaskbarPinOptions): Html {
  if (!Number.isSafeInteger(count) || count < 0) throw new Error("count must be a safe nonnegative integer");
  return html`<a class="axp-pin" title="${hint}" href="${href}" data-count="${count}"><span class="fav" aria-hidden="true">${icon}</span><span class="lbl">${label}</span></a>`;
}

export type TrayItemOptions = {
  id: string;
  href: string;
  kind: string;
  title: string;
  label: string;
  icon: Html;
  hidden?: boolean;
};

export function TrayItem({
  id,
  href,
  kind,
  title,
  label,
  icon,
  hidden = false,
}: TrayItemOptions): Html {
  if (asBool(hidden) === null) throw new Error("hidden must be a boolean");
  return html`<a id="${id}" class="axp-trayico"${hidden ? " hidden" : ""} href="${href}" data-kind="${kind}" title="${title}" aria-label="${label}">${icon}</a>`;
}

export type TaskbarTrayOptions = {
  items: TrayItemOptions[];
};

export function TaskbarTray({
  items,
}: TaskbarTrayOptions): Html {
  return html`<div id="axp-tray"><button id="axp-sound" type="button" hidden></button>${items.map(TrayItem)}<span id="axp-clock" aria-hidden="true"></span></div>`;
}

export type TaskbarOptions = {
  pins: Html;
  tray: Html;
};

export function Taskbar({
  pins,
  tray,
}: TaskbarOptions): Html {
  return html`<div id="axp-taskbar" role="navigation" aria-label="taskbar"><a id="axp-start" href="/run" aria-haspopup="dialog" aria-expanded="false"><span id="axp-cone" aria-hidden="true"></span>start<span class="axp-kbd" aria-hidden="true">⌘K</span></a><div id="axp-pins">${pins}</div><div id="axp-spacer"></div>${tray}</div>`;
}
