// Generated by tools/xp; run bun tools/gen-xp.ts. Do not edit.
import { Html, html } from "../html.ts";

export type TaskbarPinOptions = {
  href: string;
  label: string;
  hint: string;
  count: number;
  icon: Html;
};

export function TaskbarPin({
  href,
  label,
  hint,
  count,
  icon,
}: TaskbarPinOptions): Html {
  if (!Number.isSafeInteger(count) || count < 0) throw new Error("count must be a safe nonnegative integer");
  return html`<a class="axp-pin" title="${hint}" href="${href}" data-count="${count}"><span class="fav" aria-hidden="true">${icon}</span><span class="lbl">${label}</span></a>`;
}

export type TaskbarOptions = {
  pins: Html;
  tray: Html;
};

export function Taskbar({
  pins,
  tray,
}: TaskbarOptions): Html {
  return html`<div id="axp-taskbar" role="navigation" aria-label="taskbar"><a id="axp-start" href="/run" aria-haspopup="dialog" aria-expanded="false"><span id="axp-cone" aria-hidden="true"></span>start<span class="axp-kbd" aria-hidden="true">⌘K</span></a><div id="axp-pins">${pins}</div><div id="axp-spacer"></div>${tray}</div>`;
}
