// lwe-ask's Worker config, in the TypeScript format `cf migrate` writes.
//
// Generated by `cf migrate wrangler.toml --no-install` (cf 1.0.0-beta.5) on
// 2026-09-28 and then edited in three ways, each deliberate:
//
//   - The comments that lived in wrangler.toml are carried over at the keys
//     they explain. The generator drops every one of them.
//   - The import names `@cloudflare/config/public` instead of `cf/config`, for
//     the reason cf-garage/cloudflare.config.ts gives: `cf/config` is a one-line
//     re-export of that package, and depending on `cf` pins a second Miniflare
//     and Workerd into the tree.
//   - The generator's `throw new Error("Migration incomplete")` guard and its
//     two TODOs are resolved and removed; see the dependency instrumentation
//     note at the bottom.
//
// EVERY WRANGLER COMMAND THAT READS THIS FILE PASSES `--x-new-config` and runs
// from this directory, because the loader reads the working directory and
// refuses `-c`. That retires the old `-c wrangler.toml` trap on its own: the
// loader never walks up to the root wrangler.jsonc. `cf build`, `cf dev` and
// `cf deploy` work here too, since package.json names the root's wrangler (the
// `cf` CLI reads a project's OWN manifest for its dev server).
//
// The upload is byte-identical to the toml's: same index.js and source map
// sha256, measured on the migration commit with `deploy --dry-run --outdir`.
import { bindings, defineConfig, triggers } from "@cloudflare/config/public";

export default defineConfig({
  // Pinned because this deploys from its OWN directory, so wrangler resolves the
  // account from this file rather than from the root wrangler.jsonc. It
  // auto-selects only while the login sees exactly one account, and a second
  // appeared on 2026-08-07. Until the pin existed the answer came from
  // ~/.wrangler/cache/wrangler-account.json, which an interactive prompt
  // writes, so a fresh clone or a cleared cache broke the deploy. Must equal
  // wrangler.jsonc's account_id; check-infra.ts fails on drift.
  accountId: "1c99acdb6141579023fb97d24261ea58",
  worker: {
    name: "lwe-ask",
    compatibilityDate: "2026-05-01",
    // `new_module_registry` is not date-gated; the argument is at the same key
    // in the root wrangler.jsonc, and every Worker here carries it.
    compatibilityFlags: ["new_module_registry"],
    entrypoint: "src/index.ts",

    // Workers Logs, the same free tier cf-garage and lens-reader already run on.
    // lwe-ask was the ONE auxiliary Worker without it, and the gap is not
    // cosmetic: /lwe/ask/reindex is a gated route that answers 401 to a request
    // whose secret header never arrived, which is exactly what a `curl -s`
    // hides. Diagnosing that on 2026-08-21 took a live `wrangler tail` running
    // at the moment of the call, because nothing here kept a record. A route
    // that fails silently is the one that most needs a log.
    observability: {
      enabled: true,
      traces: { enabled: true, headSamplingRate: 1 },
    },

    // Live "ask a follow-up" for the Learning With Errors explainers. RAG over
    // the author's OWN essay passages (never third-party text): embed the
    // question, retrieve the most relevant verbatim passages from Vectorize, and
    // have Workers AI frame an answer grounded ONLY in those passages (with the
    // passages cited).
    //
    // Routed at the /lwe/ask endpoints only; the static /lwe/* pages AND the
    // static widget file /lwe/ask.js stay on the site Worker. NB: must NOT use
    // `/lwe/ask*` (that wildcard swallows /lwe/ask.js); the exact + subpath pair
    // below covers /lwe/ask (POST, no query) and
    // /lwe/ask/{challenge,verify,reindex} without touching ask.js.
    triggers: [
      triggers.fetch({ pattern: "aadhar.sh/lwe/ask", zone: "aadhar.sh" }),
      triggers.fetch({ pattern: "aadhar.sh/lwe/ask/*", zone: "aadhar.sh" }),
    ],

    env: {
      // Workers AI: embeddings + generation.
      AI: bindings.ai({}),

      // Vectorize: the passage index. Create with:
      //   bun run wrangler vectorize create lwe-passages --dimensions=768 --metric=cosine
      VECTORIZE: bindings.vectorize({ name: "lwe-passages" }),

      EMBED_MODEL: bindings.text("@cf/baai/bge-base-en-v1.5"), // 768-dim, matches the index
      GEN_MODEL: bindings.text("@cf/meta/llama-3.3-70b-instruct-fp8-fast"), // current (3.1-8b was deprecated 2026-05-30)
      TOP_K: bindings.text("4"),
      MAX_Q_LEN: bindings.text("400"),

      // Secrets (wrangler secret put):
      //   SIGNING_SECRET: HMAC for the CAPTCHA challenge + askToken (openssl rand -hex 32)
      //   REINDEX_SECRET: gates the /lwe/ask/reindex route
    },

    // `[dependencies_instrumentation] enabled = true` has no home in this
    // format, which is the one TODO `cf migrate` flagged. It costs nothing, for
    // the reason cf-garage measured: wrangler tests the key as
    // `enabled !== false`, so an absent block behaves exactly like the explicit
    // `true` the toml carried.
  },
});
