// gen-feeds.mjs — RSS 2.0 feeds for the three authored sections.
//
// WHY BUILD OUTPUT. A feed is a pure function of the registry, the sitemap's
// dates, and posts.json, all of which the build already has in hand. Generating
// it means there is no committed copy to fall behind and no step anyone can
// forget, the same argument the Markdown twins and the dcz deltas won. The
// Worker never sees a feed request: `.xml` under /writing, /garage, /lwe is a
// static asset served from the edge.
//
// WHY THE SITEMAP IS THE DATE SOURCE. Feed items need a date, and this site
// already maintains one per URL in public/sitemap.xml as <lastmod>. Reading it
// keeps ONE authored date per page rather than introducing a second one that
// would immediately start disagreeing. Deliberately NOT git commit dates: a
// whitespace fix would republish an item to every subscriber, and a page moved
// between files would lose its history entirely.
//
// Items with no <lastmod> are dropped rather than dated `now`. A feed reader
// treats a date as a promise about when something changed, and inventing one
// re-sorts a subscriber's timeline on every deploy.

import { readFileSync } from "node:fs";

const SITE = "https://aadhar.sh";

/** RSS is XML, and five characters decide whether it parses. */
function xmlEscape(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;").replaceAll("'", "&apos;");
}

/** RFC 822, which RSS 2.0 requires. A bare ISO date is not valid pubDate. */
export function rfc822(ymd) {
  const date = new Date(`${ymd}T12:00:00Z`);
  if (Number.isNaN(date.valueOf())) return null;
  return date.toUTCString();
}

/** Pull { path: lastmod } out of the committed sitemap. Regex rather than an XML
 *  parser because the sitemap is generated by this repo and its shape is fixed;
 *  a dependency for six lines would be the larger risk. */
export function sitemapDates(sitemapXml) {
  const dates = new Map();
  for (const entry of sitemapXml.matchAll(/<url>([\s\S]*?)<\/url>/g)) {
    const loc = entry[1].match(/<loc>\s*([^<\s]+)\s*<\/loc>/)?.[1];
    const lastmod = entry[1].match(/<lastmod>\s*([0-9]{4}-[0-9]{2}-[0-9]{2})/)?.[1];
    if (!loc || !lastmod) continue;
    dates.set(loc.replace(SITE, "") || "/", lastmod);
  }
  return dates;
}

/**
 * One feed. Items are newest first, which is the only order a reader respects.
 */
export function renderFeed({ title, description, path, items }) {
  const entries = items
    .filter((item) => item.date && rfc822(item.date))
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.title < b.title ? -1 : 1));
  const newest = entries[0]?.date;
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${xmlEscape(title)}</title>
    <link>${SITE}${xmlEscape(path)}</link>
    <atom:link href="${SITE}${xmlEscape(path)}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>${xmlEscape(description)}</description>
    <language>en</language>
${newest ? `    <lastBuildDate>${rfc822(newest)}</lastBuildDate>\n` : ""}${entries.map((item) => `    <item>
      <title>${xmlEscape(item.title)}</title>
      <link>${SITE}${xmlEscape(item.path)}</link>
      <guid isPermaLink="true">${SITE}${xmlEscape(item.path)}</guid>
      <pubDate>${rfc822(item.date)}</pubDate>
      <description>${xmlEscape(item.description)}</description>
    </item>`).join("\n")}
  </channel>
</rss>
`;
}

export const FEEDS = [
  { path: "/writing", section: "writing", title: "aadhar.sh — writing", description: "Notes, in flux." },
  { path: "/garage", section: "garage", title: "aadhar.sh — garage", description: "Prototypes and experiments: the site's workshop." },
  { path: "/lwe", section: "lwe", title: "aadhar.sh — learning with errors", description: "Chat-style explainers with live demos." },
];

/**
 * Build every feed from the committed sources.
 *
 * @returns {Map<string, string>} route ("/garage/feed.xml") to XML body.
 */
export function buildFeeds(root = ".") {
  const manifest = JSON.parse(readFileSync(`${root}/config/site-manifest.json`, "utf8"));
  const dates = sitemapDates(readFileSync(`${root}/public/sitemap.xml`, "utf8"));
  const posts = JSON.parse(readFileSync(`${root}/src/content/writing/posts.json`, "utf8"));

  // /writing entries are not registered surfaces (a post is a row in posts.json,
  // not a manifest page), so that section reads its own registry and carries its
  // own authored date. The other two project the manifest.
  const writingItems = posts.map((post) => ({
    path: `/writing/${post.slug}`,
    title: post.title,
    description: `A note: ${post.title}.`,
    date: post.date,
  }));

  const out = new Map();
  for (const feed of FEEDS) {
    const items = feed.section === "writing"
      ? writingItems
      : manifest.surfaces
        .filter((surface) => surface.section === feed.section && surface.kind === "content" && surface.path !== feed.path)
        .map((surface) => ({
          path: surface.path,
          title: surface.title,
          description: surface.description || surface.hint || "",
          date: dates.get(surface.path),
        }));
    out.set(`${feed.path}/feed.xml`, renderFeed({ ...feed, items }));
  }
  return out;
}
