// The types the Vitest pool supplies to this suite, which no package exports in
// a form `types:` can reach.
//
// TWO SEPARATE JOBS, and they fail in different ways without this file.
//
// 1. `cloudflare:test` is an AMBIENT module declaration shipped by
//    @cloudflare/vitest-pool-workers under its `./types` subpath rather than its
//    package root, so a tsconfig `types` entry cannot pull it in and the three
//    importing test files read as TS2307. Cloudflare's own setup docs use
//    exactly this reference.
//
// 2. `Cloudflare.Env` is what that module types its `env` export as, and it is
//    EMPTY here: the interface is normally generated by `wrangler types` from a
//    deploy config, and cal has no deploy config of its own (production belongs
//    to the root aadhar-sh Worker). Left empty, every `env.BOOKINGS` in the
//    suite reads as a missing property, which is a missing declaration rather
//    than a finding, and index.test.js's `{ ...baseEnv }` spread silently
//    contributes nothing to the object it builds.
//
// THE AUGMENTATION BELOW MIRRORS cal/wrangler.test.toml AND NOTHING ELSE. A
// contract test compares the two name by name, because a hand-written mirror of
// a machine-readable file is exactly the copy that rots: adding a var to the
// TOML and not here would leave the suite type-checking against a fiction, and
// the failure would be a green run. The three SECRETS the suite needs
// (SIGNING_SECRET, ICAL_URL, RESEND_API_KEY) are deliberately absent, for the
// reason vitest.config.js gives: they are not in the TOML, so tests that need
// them pass values explicitly.
/// <reference types="@cloudflare/vitest-pool-workers/types" />

declare namespace Cloudflare {
  interface Env {
    // [[kv_namespaces]]
    BOOKINGS: KVNamespace;
    // [[workflows]]
    BOOKING_WORKFLOW: Workflow;
    // [vars] — every one of them a string, which is what a Workers var is.
    HOST_TIMEZONE: string;
    WORKING_HOURS_START: string;
    WORKING_HOURS_END: string;
    WORKING_DAYS: string;
    SLOT_MINUTES: string;
    BUFFER_MINUTES: string;
    MIN_NOTICE_HOURS: string;
    MAX_LOOKAHEAD_DAYS: string;
    DAILY_LIMIT: string;
    WEEKLY_LIMIT: string;
    HOST_NAME: string;
    HOST_EMAIL: string;
    HOST_PUBLIC_URL: string;
    EVENT_TITLE: string;
    PENDING_TTL_DAYS: string;
  }
}
