// passages.js — the corpus the "ask" feature is grounded in.
//
// IMPORTANT: every passage here is from the AUTHOR'S OWN essay
// ("Privacy 2.0: PETs and the Promise of Private Shared State", by Aadharsh
// Pannirselvam, archetype.fund) — his content, used verbatim with attribution.
// Do NOT add third-party text (e.g. the programmable-cryptography PDF) here; that
// would republish someone else's copyrighted work. Third-party material can only
// inform AI-authored, attributed explanations on the page — never the corpus.
//
// The reindex route embeds each `text` and upserts it into Vectorize with the
// metadata below, so retrieval can return the real sourced passage + a link.

export const SOURCE_URL =
  "https://www.archetype.fund/media/privacy-2-0-pets-and-the-promise-of-private-shared-state-i";
export const SOURCE_TITLE = "Privacy 2.0: PETs and the Promise of Private Shared State";

// A content hash of the whole corpus, maintained by lwe-pipeline/build-corpus.mjs.
// Folded into the ask cache key, so changing any passage (then reindexing) bumps the
// version and busts every stale cached answer.
export const CORPUS_VERSION = "6d851355eb";

export const PASSAGES = [
  // ── FHE ──────────────────────────────────────────────────────────────────
  { id: "fhe-1", concept: "fhe", text:
    "Fully Homomorphic Encryption (FHE) is a form of encryption which uses a bunch of addition and multiplication on lattices and really high order polynomials with random noise and rounding to perform actions on encrypted data without ever decrypting it." },
  { id: "fhe-2", concept: "fhe", text:
    "The concept of homomorphic encryption was first theorized in the late 1970s with “privacy homomorphisms” which could enable untrusted computers to perform operations on sensitive data without needing to reveal it in plaintext. However, homomorphic encryption would remain an open problem until 2009, when cryptographer Craig Gentry described a feasible homomorphic encryption scheme using lattices to express arbitrary circuits—a fully homomorphic encryption scheme." },
  { id: "fhe-3", concept: "fhe", text:
    "A core challenge in implementing this scheme came from the randomly distributed noise that enabled Gentry's implementation of homomorphic addition and multiplication operations. Homomorphic additions add small amounts of randomly generated noise to the noise accumulated over a circuit's execution, while homomorphic multiplications multiply the same accumulated noise. When an FHE program's noise accumulates past a certain threshold in binary, it becomes indistinguishable from the encrypted data used for the underlying computation. Adding too much noise will corrupt the encrypted data, and homomorphic multiplication will do this faster than homomorphic addition." },
  { id: "fhe-4", concept: "fhe", text:
    "To mitigate this, Gentry proposed bootstrapping, a process that “refreshes” ciphertexts by homomorphically re-encrypting them using a different private key, effectively resetting a program's noise before it can bleed into the critical data and corrupt it. Bootstrapping came at the cost of speed and computational resources—it made FHE theoretically limitless but enshrined a structural tradeoff between security and usability. Gentry's initial scheme needed 30 minutes to evaluate each bit operation when it was finally implemented two years later." },
  { id: "fhe-5", concept: "fhe", text:
    "The 2013 Gentry-Sahai-Waters (GSW) scheme accelerated FHE operations from minutes to milliseconds via “leveled” circuits. However, like FHE schemes that followed, such as BGV and CKKS, it fragmented FHE into standards based on differing compilers and problem spaces. At this stage homomorphic millisecond-level logic gates remained a million times slower than traditional computing's nanosecond-level operations, and so these early schemes were impractical for use in crypto." },
  { id: "fhe-6", concept: "fhe", text:
    "Another caveat with practically applying FHE to shared state lies in decrypting outputs for use in non-FHE applications—to do so one naturally needs a decryption key. This decryption key becomes a limiter of trust assumptions and, in practice, is either controlled by a single party or a set of nodes in an MPC setting, which brings FHE back to the trust assumptions of MPC whilst being slower." },

  // ── MPC ──────────────────────────────────────────────────────────────────
  { id: "mpc-1", concept: "mpc", text:
    "Multi Party Computation (MPC) involves partitioning a secret or task over a set of distributed compute nodes to collectively perform computational work—somewhat like BitTorrent over computation." },
  { id: "mpc-2", concept: "mpc", text:
    "Secure MPC was first developed in the early 1980s, after Adi Shamir developed a “threshold scheme” for sharing secret data across multiple parties with some redundancy, for managing cryptographic keys. In 1982 Andrew Yao extended this to computation with a “Millionaire's Problem” where two parties could compare their wealth without revealing their net worths. Five years later, Goldreich et al. extended fault-tolerant computation to arbitrarily many parties—but only where over half of the N parties, an honest majority, are not adversarial. The core idea behind MPC: enabling computation that depends on shared information while preserving individual data privacy." },
  { id: "mpc-3", concept: "mpc", text:
    "By the late 1980s, the Ben-Or, Goldwasser, and Wigderson (BGW) protocol proved the ability to compute arbitrary functions under an honest majority assumption where, as long as more than two-thirds of participants are honest, a protocol could remain secure. As efficiency concerns mounted, SPDZ was created as a more viable MPC scheme for even larger majorities of dishonest actors. SPDZ introduced preprocessing that allowed secure computation even with only one honest actor, provided the malicious parties did not collude. MPC remains constrained by fundamental trade-offs: efficiency, trust assumptions, and coordination complexity." },
  { id: "mpc-4", concept: "mpc", text:
    "In contrast to TEEs, which externalize trust to the hardware manufacturer and operator of a specific node, MPC protocols decentralize trust across multiple nodes, with the assumption that a proportion of nodes aren't colluding or controlled by a malicious third party. If a majority of nodes live under the same roof, an MPC network's trust assumptions start to look similar to TEEs or a very centralized blockchain. An MPC network with tens of distributed nodes will encounter greater communication overheads (latency) relative to a two-party compute network." },

  // ── TEEs ─────────────────────────────────────────────────────────────────
  { id: "tee-1", concept: "tee", text:
    "Trusted Execution Environments (TEEs) are secure sections of physical chips that use a static but unique “root of trust” as a base secret to encrypt things. Apple has used TEEs to locally verify and store biometrics and credit card information on their hardware since 2013's iPhone 5s and 2017's T2 desktop enclave." },
  { id: "tee-2", concept: "tee", text:
    "Secret Network used a set of SGX nodes for private transactions and smart contracts. The SGX nodes held a “consensus seed” in protected memory which functioned akin to a network-wide decryption key. In October 2022, researchers used a processor architecture exploit called Aepicleak to build a proof of concept attack in which malicious actors could emulate Secret Network nodes in software to extract the network's consensus seed from memory." },
  { id: "tee-3", concept: "tee", text:
    "In many of these examples, researchers measured heat, cache activity, power consumption, and other side effects of executing programs to infer and extract secrets from operational SGX units. SGX isn't alone in being exploited via side-channels: researchers attacked AMD's SEV using malicious memory units and firmware, while a team found a physical exploit chain for Apple's hardware enclaves aboard their mobile chips." },
  { id: "tee-4", concept: "tee", text:
    "Fully trusting a closed source TEE implies trusting the TEE's firmware maintainers and manufacturers, who could feasibly have a log matching TEEs to their unique roots of trust. Fully trusting a network of closed source TEEs in operation implies trusting that the TEE isn't compromised and is operated by a non-malicious actor. As such, the value for malicious actors to exploit a TEE must be lower than the cost to perform said exploit at each of these layers." },

  // ── pipeline-managed concepts ──────────────────────────────────────────────
  // Passages added at publish time from each page's OWN explanations plus any
  // republishable sources (Wikipedia with attribution, the author's own docs).
  // NEVER third-party copyrighted text — that only informs AI-authored page copy.
  // Each carries its own { source, title } so retrieval cites the right link.
  // Regenerated by lwe-pipeline/build-corpus.mjs from lwe-ask/corpus/<concept>.json.
  // generated:corpus:start

  // dac (12)
  { id: "dac-1", concept: "dac", text:
    "A DAC turns a stream of numbers into a voltage. Multibit and delta-sigma are two designs that disagree on how to rebuild the analog wave from the samples. Multibit builds each sample as one exact level. Delta-sigma approximates that level with a coarse switch running very fast, then shapes the leftover error out of the band you can hear. Two roads to the same clean output.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-2", concept: "dac", text:
    "In a multibit DAC, an N-bit value selects one of 2^N voltages, and a resistor ladder (R-2R) sums the bits into exactly that level. A 16-bit sample picks one of 65,536 voltages. The raw output is a staircase, one flat step per sample, which an analog filter then smooths into a curve.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-3", concept: "dac", text:
    "Multibit precision turns into cost. Every step has to land on its exact voltage, so the resistors must be matched to brutal tolerances: a 20-bit ladder wants resistors good to roughly 1 part per million. That is instrumentation hardware. Schiit's Yggdrasil runs a quad of 20-bit Analog Devices AD5791 ladders, the same parts used in MRI machines, because audio-grade chips cannot hold that line.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-4", concept: "dac", text:
    "A delta-sigma DAC runs a 1-bit quantizer at 64 to 256 times the audio rate with a feedback loop, so the output works out to X(z) times z^-1 plus E(z) times (1 - z^-1). The (1 - z^-1) term is a high-pass filter on the quantization error: it pushes the noise up into ultrasonic frequencies, out of the band you hear, where a simple analog filter removes it. You trade amplitude precision for timing precision.", source: "https://en.wikipedia.org/wiki/Delta-sigma_modulation", title: "Delta-sigma modulation (Wikipedia)" },
  { id: "dac-5", concept: "dac", text:
    "Noise shaping is the heart of delta-sigma. Higher-order modulators raise the noise transfer function to (1 - z^-1) squared or cubed for a steeper tilt, pulling even more quantization noise out of the audible band. Because the quantizer is just a fast switch rather than a precise ladder, it stays cheap and very linear, and lower-bit-depth converters are easier to make highly linear.", source: "https://en.wikipedia.org/wiki/Delta-sigma_modulation", title: "Delta-sigma modulation (Wikipedia)" },
  { id: "dac-6", concept: "dac", text:
    "Nearly every DAC chip on the market today (ESS, AKM, Cirrus) is delta-sigma, because the coarse, fast, oversampled quantizer is cheap to integrate on-chip and posts excellent total-harmonic-distortion and signal-to-noise numbers. On steady-state measurements, modern delta-sigma generally beats multibit.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-7", concept: "dac", text:
    "Multibit keeps a following for two honest reasons. Coarse bits are audible when nothing shapes them away, and some listeners argue the modulator's behavior on quiet passages and on the decay of notes sounds different in ways a steady-tone measurement will not capture. The measurable gap between good modern designs is tiny and often below audibility, but the preference is real to the people who hold it and hard to reduce to a single number.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-8", concept: "dac", text:
    "The summary: multibit pays in hardware to make every level physically exact, while delta-sigma pays in cleverness to make the errors inaudible. Both arrive at clean sound by opposite routes; they just disagree about where to put the hard part. Quantization noise is audible at low bit depth, and delta-sigma's move is to keep the bit depth low but shove that noise above 20 kHz.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-9", concept: "dac", text:
    "An R-2R resistor ladder turns N bits into one voltage using only two resistor values, R and 2R, one rung per bit. From any rung, the resistance looking back toward the smaller bits always works out to R, so each rung halves the contribution of the one above it: the most significant bit lands Vref/2 at the output, the next Vref/4, then Vref/8, and so on. Adding up whichever bits are switched to Vref gives Vref times the binary value divided by 2^N, all from two resistor values repeated.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-10", concept: "dac", text:
    "In an R-2R ladder each bit's resistor sets that bit's weight, so an error in a high bit shifts the output a lot while an error in a low bit barely matters. A large enough error makes the converter non-monotonic, meaning a higher input code can produce a lower output voltage. To stay monotonic and linear, a 20-bit ladder needs resistors matched to about 1 part per million, because the most significant bit's accuracy has to beat the size of the smallest step.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-11", concept: "dac", text:
    "A DAC's raw output is a staircase (multibit) or a fast 1-bit stream (delta-sigma), and a reconstruction filter smooths it into the analog wave by removing the spectral images above the audio band. This filter is a time-versus-frequency tradeoff: a sharp, fast filter kills the images cleanly but rings in time, while a slow filter rings less but rolls off some treble and lets a little imaging through. A non-oversampling (NOS) DAC skips the filter, so there is no ringing but the images leak through; oversampling first pushes the images far up in frequency so a gentle filter can finish the job. Filter choice is also where Schiit's Mike Moffat differs, shipping a custom closed-form filter instead of the stock windowed-sinc.", source: "https://aadhar.sh/lwe/dac", title: "aadhar.sh: DACs" },
  { id: "dac-12", concept: "dac", text:
    "A reconstruction filter (anti-imaging filter) is a low-pass filter applied after a DAC to remove the spectral images that sampling creates, leaving the original baseband signal. The ideal reconstruction filter is a sinc function, a perfect brick-wall low-pass, but it is not physically realizable because it is infinitely long in time. Real filters therefore approximate it and trade off passband flatness, stopband sharpness, and time-domain ringing, which is a direct consequence of the Fourier relationship between a signal's width in time and in frequency.", source: "https://en.wikipedia.org/wiki/Reconstruction_filter", title: "Reconstruction filter (Wikipedia)" },

  // drivers (7)
  { id: "drivers-1", concept: "drivers", text:
    "Dynamic and planar magnetic headphone drivers differ in how the diaphragm is pushed. A dynamic driver attaches a voice coil to a cone and sits it in a magnet gap, so current through the coil makes a force at that one spot and the cone carries the push out to its edges. A planar magnetic driver etches the conductor across a thin flat film hung between two magnet arrays, so the force lands evenly over the whole surface.", source: "https://aadhar.sh/lwe/drivers", title: "aadhar.sh: drivers" },
  { id: "drivers-2", concept: "drivers", text:
    "Point drive versus distributed drive barely matters at low frequencies, where a cone moves as one piston either way. The split shows up at high frequencies, where the wavelength inside the diaphragm gets short. A point-driven cone has to propagate that motion outward, so the rim lags the center and the surface stops moving as one piece and breaks into modes, while a flat film driven everywhere at once stays flat.", source: "https://aadhar.sh/lwe/drivers", title: "aadhar.sh: drivers" },
  { id: "drivers-3", concept: "drivers", text:
    "Cone breakup is a source of distortion. When different parts of a diaphragm move out of step, they radiate sound that was not in the signal, which shows up as resonance peaks and extra distortion in the treble. Spreading the drive across the whole diaphragm is how planar magnetic headphones keep distortion low at high frequencies.", source: "https://aadhar.sh/lwe/drivers", title: "aadhar.sh: drivers" },
  { id: "drivers-4", concept: "drivers", text:
    "A planar magnetic diaphragm can be extremely thin and light because it is driven everywhere at once and never has to be stiff enough to stay rigid under a point load. A dynamic cone, pushed only at the voice coil, has to resist bending, which sets a floor on its mass and stiffness.", source: "https://aadhar.sh/lwe/drivers", title: "aadhar.sh: drivers" },
  { id: "drivers-5", concept: "drivers", text:
    "Planar magnetic drivers are not universal because of tradeoffs. The magnet arrays are heavy and the large flat diaphragm is inefficient, so planars tend to be bigger, heavier on the head, and hungry for amplifier power. Dynamic drivers are light, cheap, efficient, and move a lot of air easily, which makes deep bass simple and lets them run off a phone, so most headphones in the world are dynamic.", source: "https://aadhar.sh/lwe/drivers", title: "aadhar.sh: drivers" },
  { id: "drivers-6", concept: "drivers", text:
    "The honest summary of planar versus dynamic: planar trades weight and power draw for low distortion, while dynamic trades some treble cleanliness for efficiency and easy bass. Neither wins outright. A well-engineered dynamic driver can sound excellent and a sloppy planar can sound worse than a good dynamic, because the mechanism sets the tendencies while the tuning and the build decide the result.", source: "https://aadhar.sh/lwe/drivers", title: "aadhar.sh: drivers" },
  { id: "drivers-7", concept: "drivers", text:
    "A planar magnetic (or magnetostatic) transducer drives a thin diaphragm with electrically conductive traces distributed across its surface, suspended in the field of arrays of permanent magnets on one or both sides. Because the conductor covers much of the diaphragm rather than concentrating at a single voice coil, the driving force is spread out and more uniform, which tends to lower distortion at the cost of low efficiency and heavy magnet structures.", source: "https://en.wikipedia.org/wiki/Planar_magnetic_loudspeaker", title: "Planar magnetic loudspeaker (Wikipedia)" },

  // encoding (9)
  { id: "encoding-1", concept: "encoding", text:
    "One photo can produce three different file sizes because each encoder discards the detail your eye tends to skip and then packs what survives, and the three encoders push each step with different intensity. JPEG (1992) splits the image into 8x8 blocks, runs a discrete cosine transform, and rounds off the high-frequency parts. jpegli (Google, 2024) keeps the exact JPEG format but rounds smarter, fitting roughly 25 percent more quality into the same bytes as the older mozjpeg encoder. AVIF borrows AV1's video techniques, including larger blocks and sharper prediction, so it usually wins on bytes per pixel outright.", source: "https://aadhar.sh/lwe/encoding", title: "aadhar.sh: thumbnail encoding" },
  { id: "encoding-2", concept: "encoding", text:
    "jpegli writes a normal .jpg that any browser can open, just smaller, because it stays inside the JPEG bitstream; a browser from 1995 still decodes it. AVIF instead needs a modern decoder (Safari 16+, Chrome 85+). That trade between universal-but-larger and modern-but-smaller is why the photo grid ships both formats and lets the browser choose.", source: "https://aadhar.sh/lwe/encoding", title: "aadhar.sh: thumbnail encoding" },
  { id: "encoding-3", concept: "encoding", text:
    "AVIF's catch is decode support and encode time. It leans on the AV1 codec, which is slower to encode and only decodes on recent browsers, while jpegli is fast and universal. For that reason the site ships a tuned JPEG encoder for the universal fallback and uses AVIF as the primary <picture> source. That encoder was jpegli, built from source, until 2026-07; it is now zenjpeg (hybrid trellis quantization plus a search across 64 candidate progressive scan scripts), which lands a few percent under jpegli at matched quality: the browser reaches for AVIF first, and anything that cannot decode it falls back to the jpegli .jpg.", source: "https://aadhar.sh/lwe/encoding", title: "aadhar.sh: thumbnail encoding" },
  { id: "encoding-4", concept: "encoding", text:
    "Grayscale shots encode much smaller because a color image carries one luma plane (brightness) plus two chroma planes (color). Converting to grayscale deletes both chroma planes, roughly two-thirds of the color information, so the file size falls hard.", source: "https://aadhar.sh/lwe/encoding", title: "aadhar.sh: thumbnail encoding" },
  { id: "encoding-5", concept: "encoding", text:
    "Each thumbnail on the site is dual-encoded: an AVIF primary and a zenjpeg JPEG fallback inside one <picture> element, plus a 400px AVIF tier for phones. The browser loads the smallest format it can decode and never downloads the others.", source: "https://aadhar.sh/lwe/encoding", title: "aadhar.sh: thumbnail encoding" },
  { id: "encoding-6", concept: "encoding", text:
    "On one measured 400x266 photo (106,400 pixels), the encoders land at very different sizes against the lossless PNG baseline: baseline JPEG at quality 82, jpegli at quality 82 (roughly half the baseline JPEG), zenjpeg at quality 84 (the encoder the site ships), WebP at quality 80, and AVIF at quality 63, with AVIF the smallest of the lossy set. Bytes per pixel is computed by dividing each file's byte size by the pixel count, which makes the encoders directly comparable on a single photo.", source: "https://aadhar.sh/lwe/encoding", title: "aadhar.sh: thumbnail encoding" },
  { id: "encoding-7", concept: "encoding", text:
    "Chroma subsampling is a compression technique that stores color information (chroma) at lower spatial resolution than brightness information (luma), exploiting the human visual system's greater sensitivity to brightness detail than to color detail. Common schemes are written as ratios such as 4:4:4 (no subsampling), 4:2:2 (chroma sampled at half horizontal resolution), and 4:2:0 (chroma sampled at half resolution both horizontally and vertically). The savings come because the eye notices reduced color resolution far less than reduced brightness resolution.", source: "https://en.wikipedia.org/wiki/Chroma_subsampling", title: "Chroma subsampling (Wikipedia)" },
  { id: "encoding-8", concept: "encoding", text:
    "AVIF (AV1 Image File Format) is an image format that stores images or image sequences compressed with the AV1 video codec inside the ISOBMFF container. Because it reuses AV1's intra-frame coding tools, it generally achieves smaller files than JPEG and WebP at comparable quality, and it supports features such as high dynamic range, wide color gamut, alpha transparency, and both lossy and lossless compression. Browser support arrived around 2020 in Chrome and 2022 in Safari.", source: "https://en.wikipedia.org/wiki/AVIF", title: "AVIF (Wikipedia)" },
  { id: "encoding-9", concept: "encoding", text:
    "JPEG is a widely used lossy compression method for digital images, standardized in 1992, that works by transforming 8x8 pixel blocks with a discrete cosine transform and then quantizing the resulting frequency coefficients. The degree of quantization sets a tunable tradeoff between file size and image quality, and the format commonly applies chroma subsampling to reduce color data. Its near-universal decoder support is the main reason it remains a default web image format decades later.", source: "https://en.wikipedia.org/wiki/JPEG", title: "JPEG (Wikipedia)" },

  // knots (7)
  { id: "knots-1", concept: "knots", text:
    "A simple binding knot like a shoelace bow is essentially two crossings of the two ends. The only thing that separates a square (reef) knot from a granny knot is the handedness of the second crossing: if it mirrors the first crossing you get a square knot that seats flat and holds, and if it repeats the first you get a granny that capsizes and slips. Most people whose laces keep coming undone are unknowingly tying a granny bow.", source: "https://aadhar.sh/lwe/knots", title: "aadhar.sh: knots" },
  { id: "knots-2", concept: "knots", text:
    "The standard shoelace bow is cross, loop, wrap, pull. If the starting cross and the wrapping loop go the same way, the result is a granny bow that sits diagonally across the shoe and works loose. Reversing just one of the two steps gives a square bow that sits straight across the shoe and stays tied. Same moves, opposite handedness on the second step.", source: "https://aadhar.sh/lwe/knots", title: "aadhar.sh: knots" },
  { id: "knots-3", concept: "knots", text:
    "The Ian knot, from Ian Fieggen, is a speed method that lands on the same knot as the standard bow, not a different knot. You form a loop in each hand at the same time and pass them through each other in one motion, instead of making one loop and wrapping the other lace around it. Tied with the correct handedness it produces the same square bow, just much faster. Ian's Secure variant adds an extra tuck for laces that still wander.", source: "https://aadhar.sh/lwe/knots", title: "aadhar.sh: knots" },
  { id: "knots-4", concept: "knots", text:
    "Bunny ears ties a shoelace by making both loops first and then knotting the two loops like ropes. It is easy to learn but just as prone to the granny trap: tying the two ears with the same handedness as the starting cross produces a granny bow. The knot does not care which method produced the two crossings; only their relative handedness decides whether it holds or slips.", source: "https://aadhar.sh/lwe/knots", title: "aadhar.sh: knots" },
  { id: "knots-5", concept: "knots", text:
    "The whole shoelace problem reduces to one rule that runs from a reef knot on a sail to the bow on a shoe: make the two crossings oppose each other. Cross one way, then cross back the other way. Matching the handedness makes the knot slip; opposing it makes the knot hold. Everything else about the various methods is speed and style.", source: "https://aadhar.sh/lwe/knots", title: "aadhar.sh: knots" },
  { id: "knots-6", concept: "knots", text:
    "A reef knot (square knot) is an ancient binding knot used to secure a rope or line around an object, tied by making two half-knots of opposite handedness, one left-over-right and the other right-over-left. It lies flat, which is why it was used to reef sails. It is not secure as a bend for joining two separate ropes, especially of different sizes, because it can capsize and spill under load.", source: "https://en.wikipedia.org/wiki/Reef_knot", title: "Reef knot (Wikipedia)" },
  { id: "knots-7", concept: "knots", text:
    "The granny knot is a binding knot tied by making two half-knots of the same handedness. It is notorious for slipping or jamming and is generally considered inferior to the square (reef) knot, which differs only in reversing the handedness of the second half-knot. The granny is a common mistake when a square knot is intended, including in shoelace bows.", source: "https://en.wikipedia.org/wiki/Granny_knot", title: "Granny knot (Wikipedia)" },

  // pcrypto (13)
  { id: "pcrypto-1", concept: "pcrypto", text:
    "Programmable cryptography is 0xPARC's name for the second generation of cryptography, roughly the last 15 years. First-generation crypto hand-builds a bespoke protocol for each problem: RSA signs a message, and Yao's millionaire problem gets its own dedicated protocol to compare two incomes. Second-generation crypto instead hands you primitives you can program for any function you can express as code.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-2", concept: "pcrypto", text:
    "The shift to programmable cryptography is like going from single-purpose hardware (a digital alarm clock) to a general-purpose machine (a smartphone that runs whatever you compile for it). You stop inventing a new algorithm for each problem and start compiling the problem you already have into a primitive.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-3", concept: "pcrypto", text:
    "The 0xPARC primer organizes programmable cryptography into four pieces: 2PC (two-party computation), SNARKs (succinct proofs), FHE (computing on encrypted data), and ORAM (hiding which data you touch). The throughline is that all four compose into one toolkit and share a single compiler target, so each problem becomes something you encode rather than a fresh gadget you invent.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-4", concept: "pcrypto", text:
    "In two-party computation (2PC), two people compute F(x1, x2) where each knows only their own input and neither learns the other's. Yao's millionaire problem is the classic case: F is 'who earns more,' the inputs are the two incomes, and both walk away knowing the winner without learning the actual numbers. The engine underneath is a garbled circuit (one party encrypts a boolean circuit gate by gate, the other evaluates it blind) plus oblivious transfer; scaling 2PC past two parties leads to MPC.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-5", concept: "pcrypto", text:
    "A SNARK generalizes the idea of a signature into a proof of any statement shaped like 'I know X such that F(X, Y) = Z,' with F, Y, and Z public, once you encode F as equations. A signature already proves 'I know Alice's private key'; the headline SNARK example in the 0xPARC primer is 'I know M such that sha(M) = Y.' PLONK is one such proving scheme.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-6", concept: "pcrypto", text:
    "Fully homomorphic encryption (FHE) lets you encrypt your data, have a server compute on the ciphertext, and decrypt the result, while the server reads nothing. The 0xPARC primer's example is private machine translation: you send Enc(x) and get back Enc(translation), and the server never sees the plaintext.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-7", concept: "pcrypto", text:
    "ORAM (Oblivious RAM) addresses a leak that encryption alone leaves open: even with the data encrypted, a server still observes the access pattern, meaning which records you read, how often, and which ones together. ORAM scrambles each request into a batch of reads and writes so the server cannot tell which record you actually wanted.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-8", concept: "pcrypto", text:
    "The main reason programmable cryptography is not yet everywhere is cost. Proving a computation in a SNARK can run millions of times the cost of just doing the computation, so for a decade it stayed mostly theory with little implementation, until blockchains and other decentralized systems demanded it and pulled the practical work forward.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-9", concept: "pcrypto", text:
    "The unifying frame for programmable cryptography is that 2PC, MPC, SNARKs, FHE, and ORAM each earn their security guarantee from protocols and math rather than a hardware chip you have to trust. That puts them at the opposite end of the spectrum from a trusted execution environment (TEE): the same goal of computing on data nobody should see, with a different bet on where the trust lives.", source: "https://aadhar.sh/lwe/pcrypto", title: "aadhar.sh: programmable crypto" },
  { id: "pcrypto-10", concept: "pcrypto", text:
    "A zero-knowledge proof is a protocol where a prover convinces a verifier that a statement is true without revealing anything beyond the fact of its truth. It must satisfy three properties: completeness (an honest prover convinces an honest verifier of a true statement), soundness (a cheating prover cannot convince the verifier of a false statement except with negligible probability), and zero-knowledge (the verifier learns nothing other than that the statement holds).", source: "https://en.wikipedia.org/wiki/Zero-knowledge_proof", title: "Zero-knowledge proof (Wikipedia)" },
  { id: "pcrypto-11", concept: "pcrypto", text:
    "Secure multi-party computation lets several parties jointly compute a function over their inputs while keeping each input private. Its core security goals are input privacy (a party learns nothing about others' data beyond what the final output reveals) and correctness (honest parties either get the right result or detect cheating and abort). The adversary is modeled as a corrupt participant inside the protocol, one of the parties itself, who may collude with other corrupt parties.", source: "https://en.wikipedia.org/wiki/Secure_multi-party_computation", title: "Secure multi-party computation (Wikipedia)" },
  { id: "pcrypto-12", concept: "pcrypto", text:
    "Homomorphic encryption allows computation on encrypted data without first decrypting it, with results that, once decrypted, match the outcome of computing on the plaintext. Fully homomorphic encryption is the strongest variant, supporting arbitrary circuits of unbounded depth built from multiple gate types, so any computation can in principle run on encrypted inputs by an untrusted party.", source: "https://en.wikipedia.org/wiki/Homomorphic_encryption", title: "Homomorphic encryption (Wikipedia)" },
  { id: "pcrypto-13", concept: "pcrypto", text:
    "A garbled circuit, introduced by Andrew Yao, lets two mutually distrusting parties jointly evaluate a function expressed as a Boolean circuit without a trusted third party. One party encrypts the circuit by assigning random labels to each wire; the other obtains the labels for its own inputs through oblivious transfer (the sender learns nothing about which input the receiver chose) and then evaluates the garbled circuit to recover the output, so neither party learns the other's input.", source: "https://en.wikipedia.org/wiki/Garbled_circuit", title: "Garbled circuit (Wikipedia)" },

  // utf8 (10)
  { id: "utf8-1", concept: "utf8", text:
    "ASCII, defined in 1963, used 7 bits to give 128 numeric slots for characters, so a capital A is 65, a lowercase a is 97, and a space is 32. Those 128 slots only cover English letters, basic punctuation, and a few control codes, so there is no room for accented letters like e-acute, Chinese characters, or emoji.", source: "https://aadhar.sh/lwe/utf8", title: "aadhar.sh: UTF-8" },
  { id: "utf8-2", concept: "utf8", text:
    "Unicode gives every character one universal number called a code point, written in the form U+XXXX. For example, A is U+0041, the Chinese character zhong is U+4E2D, and the grinning-face emoji is U+1F600, covering roughly 150,000 characters and growing. A code point is still just a number, so a separate decision about how to store it as bytes is what an encoding actually is.", source: "https://aadhar.sh/lwe/utf8", title: "aadhar.sh: UTF-8" },
  { id: "utf8-3", concept: "utf8", text:
    "UTF-32 stores every code point as exactly 4 bytes, which makes indexing trivial because each character is the same fixed width. The cost is wasted space: plain English text becomes 4 times bigger (an A is stored as 00 00 00 41), and it breaks ASCII compatibility, so older tools and files that expect single-byte ASCII choke on it.", source: "https://aadhar.sh/lwe/utf8", title: "aadhar.sh: UTF-8" },
  { id: "utf8-4", concept: "utf8", text:
    "UTF-8 is variable-width: 1 byte for ASCII characters, 2 bytes for most Latin and accented letters, 3 bytes for most CJK characters like the Chinese zhong, and 4 bytes for emoji and rare scripts. Because the 1-byte case is identical to ASCII, old English text stays byte-for-byte the same, giving backwards compatibility for free.", source: "https://aadhar.sh/lwe/utf8", title: "aadhar.sh: UTF-8" },
  { id: "utf8-5", concept: "utf8", text:
    "UTF-8 is self-synchronizing: every byte announces whether it is a start byte or a continuation byte, so a reader that drops into the middle of a stream can still find where the next character begins. In a single UTF-8 character, the leading byte carries a prefix that says how many bytes the character spans, and each continuation byte starts with the bits 10, so reading the payload bits from each byte in order rebuilds the original code point.", source: "https://aadhar.sh/lwe/utf8", title: "aadhar.sh: UTF-8" },
  { id: "utf8-6", concept: "utf8", text:
    "In UTF-8 a CJK character such as the Chinese zhong is 3 bytes but still one code point and usually one visual glyph, so the length of text depends on whether you count bytes, code points, or grapheme clusters. Indexing Chinese characters by byte position is error-prone for exactly this reason, which is why the four-corner method indexes characters by the shape of strokes in each corner rather than by their bytes or pronunciation.", source: "https://aadhar.sh/lwe/utf8", title: "aadhar.sh: UTF-8" },
  { id: "utf8-7", concept: "utf8", text:
    "UTF-8 encodes characters using a variable width of 1 to 4 bytes. A single-byte character uses the binary form 0xxxxxxx and matches ASCII exactly; a two-byte character uses 110xxxxx followed by 10xxxxxx; three bytes use 1110xxxx plus two 10xxxxxx continuation bytes; and four bytes use 11110xxx plus three continuation bytes. The leading byte's prefix length tells a reader how many continuation bytes follow, which is what makes the encoding self-synchronizing.", source: "https://en.wikipedia.org/wiki/UTF-8", title: "UTF-8 (Wikipedia)" },
  { id: "utf8-8", concept: "utf8", text:
    "UTF-8 has been the most common character encoding on the World Wide Web since 2008, and as of early 2026 it is used by roughly 99 percent of surveyed websites. The first 128 Unicode code points map directly to ASCII, so a UTF-8 file that uses only those characters is byte-for-byte identical to an ASCII file.", source: "https://en.wikipedia.org/wiki/UTF-8", title: "UTF-8 (Wikipedia)" },
  { id: "utf8-9", concept: "utf8", text:
    "A code point is a numeric value assigned to a specific character within a coded character set. In Unicode, code points are written with the U+ prefix followed by a hexadecimal value, such as U+0041 for the letter A, and an encoding then determines how each code point becomes actual bytes: UTF-32 uses a fixed 4 bytes, UTF-16 uses one or two 2-byte units, and UTF-8 uses one to four bytes.", source: "https://en.wikipedia.org/wiki/Code_point", title: "Code point (Wikipedia)" },
  { id: "utf8-10", concept: "utf8", text:
    "Unicode is a character encoding standard, maintained by the Unicode Consortium, that aims to support text in all of the world's writing systems. Its codespace runs from U+0000 to U+10FFFF, providing more than 1.1 million possible code points, of which Version 17.0 (September 2025) assigns about 159,801 characters across 172 scripts. Unicode itself only maps characters to numbers; UTF-8, UTF-16, and UTF-32 are the transformation formats that turn those numbers into bytes.", source: "https://en.wikipedia.org/wiki/Unicode", title: "Unicode (Wikipedia)" },

  // vigenere (13)
  { id: "vigenere-1", concept: "vigenere", text:
    "A Caesar cipher shifts every letter by one fixed amount (for example A becomes D, a shift of 3). It is monoalphabetic: the same plaintext letter always maps to the same ciphertext letter, so a frequency count cracks it quickly because E stays the most common letter and is just relabeled. A Vigenere cipher uses a repeating key of shifts instead, where position 1 shifts by the first key letter, position 2 by the second, and so on, so the same plaintext letter lands as different ciphertext depending on its position. That polyalphabetic behavior flattens the frequency signal.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-2", concept: "vigenere", text:
    "A Caesar cipher is just a Vigenere with a one-letter key. The key J repeats into the keystream JJJJJJ, shifting every letter by the same 9, which is exactly a Caesar shift of 9, and the key JJJ is identical because it repeats into the same stream. A Caesar is the period-1 case, and a Vigenere is what you get once the key has more than one letter.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-3", concept: "vigenere", text:
    "A Vigenere cipher uses the alphabet's order, so a keyed alphabet scrambles which shifts apply. Kryptos K1 and K2 are Vigenere on a keyed alphabet: the tableau is built on the keyword KRYPTOS, so the working alphabet becomes KRYPTOSABCDEFGHIJLMNQUVWXZ instead of A through Z. K1's running key is PALIMPSEST and K2's is ABSCISSA, and decrypting K1's ciphertext (EMUFPHZLRFAXYUSDJKZLD...) yields Sanborn's line ending in the deliberate misspelling 'the nuance of iqlusion.'", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-4", concept: "vigenere", text:
    "Kryptos K3 plays a different game from K1 and K2: it is a transposition rather than a substitution. All the letters are correct and just rearranged by a route or columnar scheme. That split between substitution (swap the letters, keep the order) and transposition (keep the letters, shuffle the order) becomes the whole game once you reach the unsolved parts.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-5", concept: "vigenere", text:
    "A repeating Vigenere key has a period, and that period is its weakness. Kasiski spacing and the Friedman test recover the key length, after which the cipher reduces to 26 little Caesar shifts that you solve separately. An autokey kills the period because instead of repeating the keyword you extend the key with the message itself (the key first, then the plaintext), so no repeat means no period to find.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-6", concept: "vigenere", text:
    "Cracking a Kryptos-shaped cipher with no known parameters is a search over a pipeline, because you do not know the alphabet, the key, or the order of operations. The abstract toolkit includes transposition (columnar, route, rotation, skip-reads), substitution (Vigenere and the Quagmire I through IV family, which differ in which of the plaintext, ciphertext, or key alphabets are keyed, with QIII being the Kryptos one and QIV keying all three), running keys and autokeys, plus the order of stages such as transpose-then-Vigenere or Vigenere-then-transpose. You compose a candidate pipeline, run the text through it, score the output, then crank the next combination.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-7", concept: "vigenere", text:
    "To decode a stacked cipher pipeline, set every stage to decrypt and list the stages in the reverse of how the text was encoded. A Vigenere placed above a transposition is 'Vig first' and below it is 'Vig last,' and the two orders give different ciphertext. A transposition keeps every letter but shuffles their order, while a substitution swaps the letters but keeps their order.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-8", concept: "vigenere", text:
    "You tell signal from noise by the statistical shape of the letters. Random polyalphabetic text reads flat, with every letter roughly equally likely, while real language reads lumpy, with E, T, and A spiking. The Index of Coincidence captures this as the chance that two random letters of the text match: English is about 0.067 and uniform random is about 0.038, so a correct monoalphabetic decrypt jumps toward 0.067 while a wrong, still-polyalphabetic candidate sits near 0.04.", source: "https://aadhar.sh/lwe/vigenere", title: "aadhar.sh: Vigenère" },
  { id: "vigenere-9", concept: "vigenere", text:
    "The Vigenere cipher encrypts text with a series of interwoven Caesar shifts chosen by a repeating keyword, making it a polyalphabetic substitution where one plaintext letter can map to many ciphertext letters. Although a similar idea appeared earlier, the method was misattributed to Blaise de Vigenere in the 19th century, and for a long time it carried the nickname of the cipher no one could break before Friedrich Kasiski published a general method for breaking it in 1863.", source: "https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher", title: "Vigenère cipher (Wikipedia)" },
  { id: "vigenere-10", concept: "vigenere", text:
    "Kryptos is an encrypted sculpture by artist Jim Sanborn installed in 1990 on the grounds of CIA headquarters in Langley, Virginia. Its main text is divided into four sections; three of them (commonly labeled K1, K2, and K3) were solved publicly by the early 2000s, while the fourth section, K4, has remained unsolved for decades despite hints released by Sanborn.", source: "https://en.wikipedia.org/wiki/Kryptos", title: "Kryptos (Wikipedia)" },
  { id: "vigenere-11", concept: "vigenere", text:
    "The index of coincidence is the probability that two letters drawn at random from a text are the same. It is useful in cryptanalysis because it stays roughly constant under monoalphabetic substitution but drops toward the value for uniform random text under polyalphabetic encryption, which lets analysts detect a Vigenere-style cipher and estimate the key length.", source: "https://en.wikipedia.org/wiki/Index_of_coincidence", title: "Index of coincidence (Wikipedia)" },
  { id: "vigenere-12", concept: "vigenere", text:
    "Columnar transposition is a transposition cipher: it keeps every letter of the message but rearranges their order instead of substituting letters. You write the message into a grid row by row under a keyword, then read it back out one column at a time, taking the columns in the alphabetical order of the keyword's letters (ties broken left to right). The keyword KRYPTOS, for instance, ranks its seven columns 0 3 6 2 5 1 4, so you read the K column first, then O, P, R, S, T, and Y. The final row is usually ragged, so the columns differ slightly in length, and the recipient needs the keyword to rebuild the grid and reverse it. Kryptos section K3 is solved as a route transposition followed by a keyed columnar transposition, with no letter substitution at all.", source: "https://mathweb.ucsd.edu/~crypto/Projects/KarlWang/index2.html" },
  { id: "vigenere-13", concept: "vigenere", text:
    "Double columnar transposition runs the columnar step twice: the ciphertext from the first transposition is written into a fresh grid under a second keyword and read out by columns again. Chaining two passes scrambles the column structure far more thoroughly than one pass, and the hand-worked double transposition resisted practical cryptanalysis for decades. Because it is still a pure transposition, a letter-frequency count of the ciphertext matches the plaintext's exactly; only the positions move. That is why transposition is usually stacked with a substitution stage such as Vigenere, so the two together hide both the letters and their order.", source: "https://mathweb.ucsd.edu/~crypto/Projects/KarlWang/index2.html" },
  // generated:corpus:end
];
